### ISSUE TITLE
Reserved slots calculation

### ISSUE THREAD

**Issue by Lukasz1928** [srsly4/pcoip-pool-manager#7]
Algorithm used for calculation of number of reserved slots in Pools does not compute it correctly. Assuming there are 10 reserved machines from 10:00 to 11:00, and 20 from 11:00 to 12:00, the result of our calculation for time interval of 11:00-13:00 will be 30, but it should be 20.

**Comment by Maheliusz** [comment]
Naprawione w PCOIPP-28
